### ISSUE TITLE
Internal error on command:"AUTO_OFFSET_Z"

### ISSUE THREAD

**Issue by AndreyShpilevoy** [hawkeyexp/auto_offset_z#5]
I updated my 3d Printer after a long time and faced with the next issue:

```
AutoOffsetZ: Probing endstop ...
Internal error on command:"AUTO_OFFSET_Z"
Traceback (most recent call last):
  File "/home/kto/klipper/klippy/gcode.py", line 211, in _process_commands
    handler(gcmd)
  File "/home/kto/klipper/klippy/gcode.py", line 137, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/kto/klipper/klippy/extras/auto_offset_z.py", line 135, in cmd_AUTO_OFFSET_Z
    zendstop = self.printer.lookup_object('probe').run_probe(gcmd)
AttributeError: 'BLTouchProbe' object has no attribute 'run_probe'
Transition to shutdown state: Internal error on command:"AUTO_OFFSET_Z"
```

Can you check it?

**Comment by AndreyShpilevoy** [comment]
auto_offset_z
v0.0.5-0-g200a810b

crowsnest
v4.1.9-1-gd75a3aeb

klipper
v0.12.0-259-g34732f85

mainsail
v2.11.2

mainsail-config
v1.2.1-0-ge57810d5

moonraker
v0.8.0-384-g8f3b30a0

sonar
v0.1.3-1-geacc498a

timelapse
v0.0.1-143-gc7fff11e

System
OS-Packages

**Comment by AndreyShpilevoy** [comment]
Maybe it will be possible to use this function from `probe`
https://github.com/Klipper3d/klipper/blob/0087f04cc370cd542069940f0ed10c583de158ee/klippy/extras/probe.py#L488
instead of `self.printer.lookup_object('probe').run_probe(gcmd)`?
